name: CD - Dev

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dev:
    name: Dev
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: dev
    secrets: inherit
