name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: 'CI'
    runs-on: ubuntu-latest

    steps:
      - name: Building Code
        run: echo "Code build successful"
